/**
 * Produces the weekly ops report and the onboarding send list from the
 * latest snapshot. Pure computation; no network.
 *
 *   npm run ops:weekly
 *
 * Writes:
 *   ops/reports/YYYY-MM-DD.md     the report a human reads
 *   ops/data/sendlist.json        emails to send (the scheduled routine sends them, then runs ops:mark-sent)
 *   ops/feedback/BACKLOG.md       clustered feedback, regenerated
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { summarise } from '../../src/lib/analytics.ts';
import { isoDate } from '../../src/lib/dates.ts';
import { clusterFeedback } from '../../src/ops/feedback.ts';
import { alerts } from '../../src/ops/monitor.ts';
import { finalise, plannedEmails } from '../../src/ops/onboarding.ts';
import { weeklyReport } from '../../src/ops/report.ts';
import type { SentLog, Snapshot } from '../../src/ops/types.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const dataDir = join(root, 'ops', 'data');
const reportsDir = join(root, 'ops', 'reports');

function readJson<T>(path: string, fallback: T): T {
  if (!existsSync(path)) return fallback;
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

function readEnv(key: string, fallback: string): string {
  if (process.env[key]) return process.env[key] as string;
  const envPath = join(root, '.env');
  if (!existsSync(envPath)) return fallback;
  const line = readFileSync(envPath, 'utf8')
    .split('\n')
    .find((l) => l.startsWith(`${key}=`));
  return line ? line.slice(key.length + 1).trim() || fallback : fallback;
}

const empty: Snapshot = { takenAt: 0, siteUp: null, teachers: [], events: [], feedback: [], billing: [], students: [] };
const snap = readJson<Snapshot>(join(dataDir, 'snapshot.json'), empty);
const prev = readJson<Snapshot | null>(join(dataDir, 'snapshot.previous.json'), null);
const sent = readJson<SentLog>(join(dataDir, 'sent.json'), {});
const now = Date.now();

const summary = summarise(snap.teachers, snap.events, now);
const alertList = alerts(snap, prev, now);
const clusters = clusterFeedback(snap.feedback);
const emails = finalise(plannedEmails(snap, sent, now), readEnv('VITE_PUBLIC_URL', 'https://practice-slip.web.app'), readEnv('VITE_SUPPORT_EMAIL', 'hello@example.com'));
const date = isoDate(new Date(now));

if (snap.takenAt === 0) alertList.unshift({ level: 'info', message: 'No snapshot yet: run `npm run ops:snapshot` with credentials. Numbers below are zeros.' });

const report = weeklyReport({ date, summary, alerts: alertList, clusters, emails });

mkdirSync(reportsDir, { recursive: true });
mkdirSync(dataDir, { recursive: true });
mkdirSync(join(root, 'ops', 'feedback'), { recursive: true });
writeFileSync(join(reportsDir, `${date}.md`), report);
writeFileSync(join(dataDir, 'sendlist.json'), JSON.stringify(emails, null, 2));
writeFileSync(
  join(root, 'ops', 'feedback', 'BACKLOG.md'),
  `# Feedback backlog\n\nRegenerated by \`npm run ops:weekly\` on ${date}. Edit the "Status" lines by hand; the clusters are recomputed each week.\n\n${clusters.length === 0 ? '_No feedback yet._' : clusters.map((c) => `## ${c.label} (${c.count})\n\nStatus: open\n\n${c.samples.map((s) => `- "${s}"`).join('\n')}\n`).join('\n')}`,
);

console.log(report);
console.log(`\nWrote ops/reports/${date}.md and ops/data/sendlist.json (${emails.length} email${emails.length === 1 ? '' : 's'}).`);
